---
name: Validate renovate config
on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache (npm)
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
      - name: Validate renovate config
        run: |
          for file in *.json
          do
            echo "[CI] Let's validate $file"
            cp $file renovate.json
            npx --package renovate -c 'renovate-config-validator'
            rm renovate.json
          done
