---
name: Validate renovate config
on:
  schedule:
    - cron:  '5 4 7 * *'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [ lts/* ]
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Validate renovate config
        run: |
          for file in *.json
          do
            echo "[CI] Let's validate $file"
            cp $file renovate.json
            npx --package renovate -c 'renovate-config-validator'
            rm renovate.json
          done
