---
name: Validate renovate config
on:
  schedule:
    - cron:  '5 4 7 * *'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [ lts/* ]
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Validate renovate config
        run: |
          for file in *.json
          do
            echo "[CI] Let's validate $file"
            cp $file renovate.json
            npx --package renovate -c 'renovate-config-validator'
            rm renovate.json
          done
